language: cpp
compiler: clang
matrix:
  include:
    - os: linux
      sudo: required
      env: CXX_COMPILER=/usr/bin/clang++-7 CC_COMPILER=/usr/bin/clang-7
      dist: xenial
      cache: ccache
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - ninja-build
            - clang-7
            - clang++-7
            - clang-format-7
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
      script:
        - export CC=${CC_COMPILER}
        - export CXX=${CXX_COMPILER}
        - ./travis.sh
    - os: linux
      sudo: required
      env: CXX_COMPILER=gcc++ CC_COMPILER=gcc
      dist: trusty
      cache: ccache
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
      script:
        - export CC=${CC_COMPILER}
        - export CXX=${CXX_COMPILER}
        - ./travis.sh
    - os: linux
      sudo: required
      env: CHECK=clang-format
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-format-7
      script: ./travis.sh
    - os: osx
      sudo: false
      osx_image: xcode10
      cache: ccache
      script:
        - ./travis.sh
