dist: xenial
sudo: require
language: cpp
compiler: clang
os:
    - linux
    - osx
env:
  - CXX_COMPILER=/usr/bin/clang++-7 CC_COMPILER=/usr/bin/clang-7
  - CXX_COMPILER=gcc++ CC_COMPILER=gcc
  - CHECK=clang-format
addons:
  apt:
    packages:
      - ninja-build
      - clang-7
      - clang++-7
      - clang-format-7
      - libglu1-mesa-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - xorg-dev
      - libsdl2-dev
      - libglew-dev
      - libsndio-dev
      - libxkbcommon-dev
script:
    - export CC=${CC_COMPILER}
    - export CXX=${CXX_COMPILER}
    - ./travis.sh
